### ISSUE TITLE
Add way of setting sslEnabled / sslInvalidHostNameAllowed

### ISSUE THREAD

**Issue by meakinsl** [meltmedia/dropwizard-mongo#15]
Be good to be able to set sslEnabled / sslInvalidHostNameAllowed or to pass in a MongoClientOptions class that is then passed on into MongoClient constructor.

Kind Regards,

Lawrence

**Comment by ctrimble** [comment]
Would exposing a `MongoClientOptions.Builder` in the bundle builder work for you?  Something like:

```
.addClientOptions(b->b
  .sslEnabled(true)
  .sslInvalidHostNameAllowed(true))
```

**Comment by meakinsl** [comment]
Hi,


Many thanks for quick reply, exposing a MongoClientOptions will be great as at the moment with it inside the buildClient method there is no way of overriding any of the settings available on the mongo client other than the write concern you expose.


I wander given SSL is now available in 3.4 community edition if it is worth adding that flag to the MongoConfiguration class as likely to be one people might want to override.  Not a problem if not as I have simply extended your MongoConfiguration class and added the flag in order to get it configurable via the yaml file.


Kind Regards,


Lawrence

________________________________

**Comment by ctrimble** [comment]
The change is now available in develop and a new 0.5.0-SNAPSHOT version has been deployed.

**Comment by meakinsl** [comment]
Christian,


Apologies for delay in replying been on vacation for couple of days, linked to snapshot this morning and can see that you have added all the options to the configuration file which is great, simply set the sslEnabled in the config.yaml and was picked up fine in client.  Do you know when will be released officially as 0.5.0 ?


Kind Regards,


Lawrence

________________________________

**Comment by ctrimble** [comment]
@meakinsl I was just waiting for some positive feedback that the situation had improved.  I will get a release onto central today.

**Comment by ctrimble** [comment]
@meakinsl It looks like the 0.5.0 artifact is now available on central.

**Comment by meakinsl** [comment]
Christian,


Many thanks for making these changes so quickly, we are now using 0.5.0 successfully in our Mongo environments.


Kind Regards,


Lawrence

________________________________
